### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by open4profit** [lytves/twitter-lists-bot#1]
TG_YOUR_TELEGRAM_PRIVATE_CHAT_ID = ...
Does the chat_id comes under double quotes?
is this still working...
i using same but not working

**Comment by lytves** [comment]
Hi.

CHAT_ID is the numeric, that's why you don't need quotes. Yeah, the bot is working perfectly.
Look if you complete all conditions of the API of twitter, it's a quite complicated to activate Twitter API application as I remember.

Try to send messages from bot without twitter and then if all works good, test it with the full functionality.
